import json

base_characters = [
  {"name": "Superman", "image": "🦸‍♂️", "traits": {"isReal": False, "isMale": True, "hasSuperpowers": True, "wearsCape": True, "isDC": True, "isMarvel": False, "isAlien": True, "wearsGlasses": True}},
  {"name": "Batman", "image": "🦇", "traits": {"isReal": False, "isMale": True, "hasSuperpowers": False, "wearsCape": True, "isDC": True, "isMarvel": False, "isBillionaire": True, "isOrphan": True}},
  {"name": "Spider-Man", "image": "🕷️", "traits": {"isReal": False, "isMale": True, "hasSuperpowers": True, "wearsCape": False, "isDC": False, "isMarvel": True, "isTeenager": True, "isOrphan": True}},
  {"name": "Wonder Woman", "image": "🦸‍♀️", "traits": {"isReal": False, "isFemale": True, "hasSuperpowers": True, "wearsCape": False, "isDC": True, "isMarvel": False, "usesWeapons": True, "isGod": True}},
  {"name": "Taylor Swift", "image": "🎤", "traits": {"isReal": True, "isFemale": True, "isMusician": True, "isAmerican": True, "isActor": False, "isBlonde": True}},
  {"name": "Elon Musk", "image": "🚀", "traits": {"isReal": True, "isMale": True, "isBillionaire": True, "isTech": True, "isMusician": False, "isAmerican": False, "isAfrican": True}},
  {"name": "Barack Obama", "image": "🇺🇸", "traits": {"isReal": True, "isMale": True, "isPolitician": True, "isAmerican": True, "isBlack": True, "isPresident": True}},
  {"name": "Donald Trump", "image": "🇺🇸", "traits": {"isReal": True, "isMale": True, "isPolitician": True, "isAmerican": True, "isBillionaire": True, "isPresident": True, "isBlonde": True}},
  {"name": "Albert Einstein", "image": "🧠", "traits": {"isReal": True, "isMale": True, "isScientist": True, "isAlive": False, "isGerman": True, "hasMustache": True}},
  {"name": "Mickey Mouse", "image": "🐭", "traits": {"isReal": False, "isMale": True, "isAnimal": True, "isDisney": True, "wearsGloves": True}},
  {"name": "Harry Potter", "image": "⚡", "traits": {"isReal": False, "isMale": True, "hasMagic": True, "isMovieCharacter": True, "isBritish": True, "wearsGlasses": True, "isOrphan": True}},
  {"name": "Hermione Granger", "image": "📖", "traits": {"isReal": False, "isFemale": True, "hasMagic": True, "isMovieCharacter": True, "isBritish": True, "isSmart": True}},
  {"name": "Darth Vader", "image": "🌑", "traits": {"isReal": False, "isMale": True, "isMovieCharacter": True, "isSciFi": True, "isVillain": True, "wearsCape": True, "wearsHelmet": True, "isFather": True}},
  {"name": "Luke Skywalker", "image": "⚔️", "traits": {"isReal": False, "isMale": True, "isMovieCharacter": True, "isSciFi": True, "usesWeapons": True, "hasMagic": True}},
  {"name": "Pikachu", "image": "⚡", "traits": {"isReal": False, "isAnimal": True, "isAnime": True, "isVideoGame": True, "isYellow": True, "hasSuperpowers": True}},
  {"name": "Mario", "image": "🍄", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "isNintendo": True, "hasMustache": True, "wearsHat": True, "isItalian": True}},
  {"name": "Luigi", "image": "🍄", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "isNintendo": True, "hasMustache": True, "wearsHat": True, "isGreen": True, "isItalian": True}},
  {"name": "Sonic the Hedgehog", "image": "🦔", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "isAnimal": True, "isBlue": True, "hasSuperpowers": True}},
  {"name": "Goku", "image": "🐉", "traits": {"isReal": False, "isMale": True, "isAnime": True, "hasSuperpowers": True, "isAlien": True, "isFather": True}},
  {"name": "Naruto", "image": "🦊", "traits": {"isReal": False, "isMale": True, "isAnime": True, "hasSuperpowers": True, "isNinja": True, "isBlonde": True, "isOrphan": True}},
  {"name": "Michael Jackson", "image": "🕺", "traits": {"isReal": True, "isMale": True, "isMusician": True, "isAlive": False, "isAmerican": True, "isBlack": True}},
  {"name": "Cristiano Ronaldo", "image": "⚽", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isSoccer": True, "isPortuguese": True}},
  {"name": "Lionel Messi", "image": "🏆", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isSoccer": True, "isArgentine": True, "hasBeard": True}},
  {"name": "LeBron James", "image": "🏀", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isBasketball": True, "isAmerican": True, "isBlack": True}},
  {"name": "Steve Jobs", "image": "📱", "traits": {"isReal": True, "isMale": True, "isTech": True, "isAlive": False, "isAmerican": True, "wearsGlasses": True}},
  {"name": "Sherlock Holmes", "image": "🔍", "traits": {"isReal": False, "isMale": True, "isDetective": True, "isBritish": True, "isSmart": True}},
  {"name": "SpongeBob SquarePants", "image": "🧽", "traits": {"isReal": False, "isMale": True, "isCartoon": True, "livesInWater": True, "isYellow": True}},
  {"name": "Shrek", "image": "🧅", "traits": {"isReal": False, "isMale": True, "isMovieCharacter": True, "isGreen": True, "isOgre": True}},
  {"name": "Bill Gates", "image": "💻", "traits": {"isReal": True, "isMale": True, "isTech": True, "isBillionaire": True, "isAmerican": True, "wearsGlasses": True}},
  {"name": "Mark Zuckerberg", "image": "🌐", "traits": {"isReal": True, "isMale": True, "isTech": True, "isBillionaire": True, "isAmerican": True}},
  {"name": "MrBeast", "image": "🎥", "traits": {"isReal": True, "isMale": True, "isYouTuber": True, "isAmerican": True, "isPhilanthropist": True}},
  {"name": "PewDiePie", "image": "🎮", "traits": {"isReal": True, "isMale": True, "isYouTuber": True, "isSwedish": True, "isVideoGamePlayer": True}},
  {"name": "Gordon Ramsay", "image": "🍳", "traits": {"isReal": True, "isMale": True, "isChef": True, "isBritish": True, "isTvPersonality": True}},
  {"name": "Iron Man", "image": "🦾", "traits": {"isReal": False, "isMale": True, "isMarvel": True, "isBillionaire": True, "usesWeapons": True, "isScientist": True, "hasArmor": True}},
  {"name": "Captain America", "image": "🛡️", "traits": {"isReal": False, "isMale": True, "isMarvel": True, "isSoldier": True, "usesWeapons": True, "isAmerican": True}},
  {"name": "Thanos", "image": "🌌", "traits": {"isReal": False, "isMale": True, "isMarvel": True, "isVillain": True, "isAlien": True, "isPurple": True}},
  {"name": "Joker", "image": "🤡", "traits": {"isReal": False, "isMale": True, "isDC": True, "isVillain": True, "isCrazy": True, "hasFacePaint": True}},
  {"name": "Homer Simpson", "image": "🍩", "traits": {"isReal": False, "isMale": True, "isCartoon": True, "isYellow": True, "isFather": True, "isAmerican": True}},
  {"name": "Peter Griffin", "image": "🍺", "traits": {"isReal": False, "isMale": True, "isCartoon": True, "isFather": True, "isAmerican": True, "wearsGlasses": True}},
  {"name": "Kanye West", "image": "🐻", "traits": {"isReal": True, "isMale": True, "isMusician": True, "isAmerican": True, "isBlack": True}},
  {"name": "Eminem", "image": "🎤", "traits": {"isReal": True, "isMale": True, "isMusician": True, "isAmerican": True}},
  {"name": "Drake", "image": "🦉", "traits": {"isReal": True, "isMale": True, "isMusician": True, "isCanadian": True, "isBlack": True}},
  {"name": "Wolverine", "image": "🐺", "traits": {"isReal": False, "isMale": True, "isMarvel": True, "hasSuperpowers": True, "isCanadian": True, "usesWeapons": True}},
  {"name": "Deadpool", "image": "⚔️", "traits": {"isReal": False, "isMale": True, "isMarvel": True, "hasSuperpowers": True, "usesWeapons": True, "isCanadian": True, "wearsMask": True}},
  {"name": "Link", "image": "🗡️", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "isNintendo": True, "usesWeapons": True, "isElf": True, "isGreen": True}},
  {"name": "Zelda", "image": "👑", "traits": {"isReal": False, "isFemale": True, "isVideoGame": True, "isNintendo": True, "hasMagic": True, "isPrincess": True}},
  {"name": "Samus Aran", "image": "🚀", "traits": {"isReal": False, "isFemale": True, "isVideoGame": True, "isNintendo": True, "hasArmor": True, "isSciFi": True}},
  {"name": "Master Chief", "image": "🟢", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "isSciFi": True, "hasArmor": True, "isSoldier": True, "isGreen": True}},
  {"name": "Kratos", "image": "🪓", "traits": {"isReal": False, "isMale": True, "isVideoGame": True, "usesWeapons": True, "isGod": True, "isBald": True, "hasBeard": True}},
  {"name": "Keanu Reeves", "image": "🕶️", "traits": {"isReal": True, "isMale": True, "isActor": True, "isCanadian": True, "hasBeard": True}},
  {"name": "Tom Cruise", "image": "✈️", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAmerican": True}},
  {"name": "Leonardo DiCaprio", "image": "🎬", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAmerican": True}},
  {"name": "Johnny Depp", "image": "🏴‍☠️", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAmerican": True}},
  {"name": "Will Smith", "image": "👽", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAmerican": True, "isBlack": True, "isMusician": True}},
  {"name": "Queen Elizabeth II", "image": "👑", "traits": {"isReal": True, "isFemale": True, "isBritish": True, "isAlive": False, "isQueen": True}},
  {"name": "William Shakespeare", "image": "📜", "traits": {"isReal": True, "isMale": True, "isWriter": True, "isBritish": True, "isAlive": False}},
  {"name": "Abraham Lincoln", "image": "🎩", "traits": {"isReal": True, "isMale": True, "isPresident": True, "isAmerican": True, "isAlive": False, "hasBeard": True}},
  {"name": "George Washington", "image": "🇺🇸", "traits": {"isReal": True, "isMale": True, "isPresident": True, "isAmerican": True, "isAlive": False, "isSoldier": True}},
  {"name": "Nelson Mandela", "image": "🇿🇦", "traits": {"isReal": True, "isMale": True, "isPolitician": True, "isAfrican": True, "isAlive": False, "isBlack": True}},
  {"name": "Cleopatra", "image": "🇪🇬", "traits": {"isReal": True, "isFemale": True, "isAfrican": True, "isQueen": True, "isAlive": False}},
  {"name": "Marilyn Monroe", "image": "👗", "traits": {"isReal": True, "isFemale": True, "isActor": True, "isAmerican": True, "isBlonde": True, "isAlive": False}},
  {"name": "Muhammad Ali", "image": "🥊", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isAmerican": True, "isBlack": True, "isAlive": False}},
  {"name": "Bruce Lee", "image": "🥋", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAthlete": True, "isAsian": True, "isAlive": False}},
  {"name": "Jackie Chan", "image": "🐉", "traits": {"isReal": True, "isMale": True, "isActor": True, "isAsian": True, "isAlive": True}},
  {"name": "John Cena", "image": "💪", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isActor": True, "isAmerican": True}},
  {"name": "The Rock (Dwayne Johnson)", "image": "🪨", "traits": {"isReal": True, "isMale": True, "isAthlete": True, "isActor": True, "isAmerican": True, "isBald": True}},
  {"name": "Arnold Schwarzenegger", "image": "🤖", "traits": {"isReal": True, "isMale": True, "isActor": True, "isPolitician": True, "isAthlete": True}},
  {"name": "Oprah Winfrey", "image": "📺", "traits": {"isReal": True, "isFemale": True, "isTvPersonality": True, "isAmerican": True, "isBillionaire": True, "isBlack": True}},
  {"name": "Snoop Dogg", "image": "🌿", "traits": {"isReal": True, "isMale": True, "isMusician": True, "isAmerican": True, "isBlack": True}},
  {"name": "Rihanna", "image": "☂️", "traits": {"isReal": True, "isFemale": True, "isMusician": True, "isBlack": True, "isBillionaire": True}},
  {"name": "Beyonce", "image": "🐝", "traits": {"isReal": True, "isFemale": True, "isMusician": True, "isAmerican": True, "isBlack": True}},
  {"name": "Elsa", "image": "❄️", "traits": {"isReal": False, "isFemale": True, "isDisney": True, "hasMagic": True, "isPrincess": True, "isBlonde": True}},
  {"name": "Anna", "image": "⛄", "traits": {"isReal": False, "isFemale": True, "isDisney": True, "isPrincess": True}},
  {"name": "Moana", "image": "🌊", "traits": {"isReal": False, "isFemale": True, "isDisney": True, "isPrincess": True, "livesInWater": False}},
  {"name": "Ariel", "image": "🧜‍♀️", "traits": {"isReal": False, "isFemale": True, "isDisney": True, "isPrincess": True, "livesInWater": True, "hasMagic": False}}
]

with open('static/data/characters.json', 'w') as f:
    json.dump(base_characters, f, indent=2)
